-- Align profiles table with the required intelligence schema

ALTER TABLE "profiles" ADD COLUMN "country_name" TEXT;

UPDATE "profiles" AS p
SET "country_name" = COALESCE(c."country_name", p."country_id")
FROM (
  VALUES
    ('AO', 'Angola'),
    ('AU', 'Australia'),
    ('BF', 'Burkina Faso'),
    ('BI', 'Burundi'),
    ('BJ', 'Benin'),
    ('BR', 'Brazil'),
    ('BW', 'Botswana'),
    ('CA', 'Canada'),
    ('CD', 'DR Congo'),
    ('CF', 'Central African Republic'),
    ('CG', 'Republic of the Congo'),
    ('CI', 'Côte d''Ivoire'),
    ('CM', 'Cameroon'),
    ('CN', 'China'),
    ('CV', 'Cape Verde'),
    ('DE', 'Germany'),
    ('DJ', 'Djibouti'),
    ('DZ', 'Algeria'),
    ('EG', 'Egypt'),
    ('EH', 'Western Sahara'),
    ('ER', 'Eritrea'),
    ('ET', 'Ethiopia'),
    ('FR', 'France'),
    ('GA', 'Gabon'),
    ('GB', 'United Kingdom'),
    ('GH', 'Ghana'),
    ('GM', 'Gambia'),
    ('GN', 'Guinea'),
    ('GQ', 'Equatorial Guinea'),
    ('GW', 'Guinea-Bissau'),
    ('IN', 'India'),
    ('JP', 'Japan'),
    ('KE', 'Kenya'),
    ('KM', 'Comoros'),
    ('LR', 'Liberia'),
    ('LS', 'Lesotho'),
    ('LY', 'Libya'),
    ('MA', 'Morocco'),
    ('MG', 'Madagascar'),
    ('ML', 'Mali'),
    ('MR', 'Mauritania'),
    ('MU', 'Mauritius'),
    ('MW', 'Malawi'),
    ('MZ', 'Mozambique'),
    ('NA', 'Namibia'),
    ('NE', 'Niger'),
    ('NG', 'Nigeria'),
    ('RW', 'Rwanda'),
    ('SC', 'Seychelles'),
    ('SD', 'Sudan'),
    ('SL', 'Sierra Leone'),
    ('SN', 'Senegal'),
    ('SO', 'Somalia'),
    ('SS', 'South Sudan'),
    ('ST', 'São Tomé and Príncipe'),
    ('SZ', 'Eswatini'),
    ('TD', 'Chad'),
    ('TG', 'Togo'),
    ('TN', 'Tunisia'),
    ('TZ', 'Tanzania'),
    ('UG', 'Uganda'),
    ('US', 'United States'),
    ('ZA', 'South Africa'),
    ('ZM', 'Zambia'),
    ('ZW', 'Zimbabwe')
) AS c("country_id", "country_name")
WHERE p."country_id" = c."country_id";

ALTER TABLE "profiles"
  ALTER COLUMN "name" TYPE VARCHAR(255) USING "name"::VARCHAR(255),
  ALTER COLUMN "gender" TYPE VARCHAR(16) USING "gender"::VARCHAR(16),
  ALTER COLUMN "gender" SET NOT NULL,
  ALTER COLUMN "gender_probability" SET NOT NULL,
  ALTER COLUMN "age" SET NOT NULL,
  ALTER COLUMN "age_group" TYPE VARCHAR(16) USING "age_group"::VARCHAR(16),
  ALTER COLUMN "age_group" SET NOT NULL,
  ALTER COLUMN "country_id" TYPE VARCHAR(2) USING "country_id"::VARCHAR(2),
  ALTER COLUMN "country_id" SET NOT NULL,
  ALTER COLUMN "country_name" TYPE VARCHAR(255) USING "country_name"::VARCHAR(255),
  ALTER COLUMN "country_name" SET NOT NULL,
  ALTER COLUMN "country_probability" SET NOT NULL;

ALTER TABLE "profiles" DROP COLUMN "sample_size";